version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/simpleAppDevOpsCA
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@7.24.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install       
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:17
    steps:
      - run:
          name: deploy-application
          command: >
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-154-201-66.eu-west-1.compute.amazonaws.com "rm -rf simpleAppDevOpsCA/; git clone git@github.com:RubyK01/simpleAppDevOpsCA.git; source simpleAppDevOpsCA/deploy.sh"